export const GET_USERS = 'GET_USERS'
export const GET_USER = 'GET_USER'

export const GET_USER_ORDERS = 'GET_USER_ORDERS'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const USER_EXISTS_ERROR = 'USER_EXISTS_ERROR'
export const EMAIL_EXISTS_ERROR = 'EMAIL_EXISTS_ERROR'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

